name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate snake game
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: kisetzuu
          svg_out_path: dist/github-snake.svg

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/github-snake.svg
          git commit -m "Generate snake game" -a || echo "No changes to commit"
          git push
